// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeabsvryjvqyqzcdikch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlYWJzdnJ5anZxeXF6Y2Rpa2NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NjYwMDUsImV4cCI6MjA2MjE0MjAwNX0.eFp1X-Oe01p4xwSzEmcvYYfshsbOywwbtutb2uEhqQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);